<div class="container-fluid cls" id="menu">
    <div class="row nav-bar-menu">
        <div class="col-md-2 nav-category">
            <span class="category">Danh Mục</span>
        </div>
        <div class="col-md-10">
            <div class="list-menu">
                <ul>
                    <li><a href="#">DEAL Mới</a></li>
                    <li><a href="#">DEAL Bán Chạy</a></li>
                    <li><a href="#">DEAL Hot</a></li>
                    <li><a href="#">Thông Tin</a></li>
                    <li><a href="#">Liên Hệ</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid" id="top-home">
    <div class="row">
        <div class="hidden-sm col-md-3 col-lg-2 ">
            <?php echo $this->navLeftHomePage('default') ?>
        </div>
        <div class="col-sm-6 col-md-6">
            <?php echo $this->slideHomeTop('default') ?>
        </div>
        <div class="col-sm-3 col-lg-2 col-md-3 ">
            <?php echo $this->hotDealProducts() ?>
        </div>
        <div class="hidden-md col-sm-3 col-lg-2">
            <?php echo $this->news()?>
        </div>
        <div class="hidden-md col-sm-3 col-lg-2">
            <?php echo $this->history()?>
        </div>
    </div>
</div>
<div class="container-fluid" id="home">
    <div class="row">
        <?php echo $this->productHomeTabs()?>
    </div>
    <div class="row" id="middle-home">
        <?php echo $this->productsByCategory(139) ?>
    </div>
    <div class="row">
        <?php echo $this->productsByCategory(133) ?>
    </div>
    <div class="row">
        <?php echo $this->productsByCategory(137) ?>
    </div>
</div>
<?php echo $this->miniBarMenu()?>
    <!--<div class="col-md-2 col-right">
        <?php /*echo $this->news() */?>
        <?php /*echo $this->support() */?>
        <?php /*echo $this->nominationProducts('nomination-product') */?>
    </div>
</div>
</div>-->
<?php echo $this->showModal()?>