<!--  start block bar head module -->
<div class="bar-top" id="bartop">
    <div class="bar-top-cont">
        <ul class="bar-top-left">
            <li><a href="" title="Xu hướng">Xu hướng</a></li>
            <li><a href="<?php echo $this->view->url('productProperties',array('action' => 'san-pham-khuyen-mai','extension' => 'html'))?>" title="Khuyến mãi">Khuyến mãi</a></li>
            <li><a href="<?php echo $this->view->url('productProperties',array('action' => 'san-pham-ban-chay','extension' => 'html'))?>" title="Bán chạy">Bán chạy</a></li>
            <li class="tlds"><a href="" title="Tích lũy điểm sen">Tích lũy điểm thưởng</a></li>
            <li>
                <a class="tl" href="" title="Nhịp sống">Tin Tức</a>
                <ul class="sub-blog-sendo">
                    <li><a title="Thời trang" href="">Thời trang</a>
                    </li>
                    <li><a title="Làm đẹp" href="">Làm đẹp</a></li>
                    <li><a title="Gia đình" href="" >Giải trí</a></li>
                    <li><a title="Gia đình" href="" >Gia đình</a></li>
                    <li><a title="Cẩm nang" href="" target="_blank">Cẩm nang</a></li>
                    <li><a title="Tin tức" href="" target="_blank">Tin tức</a></li>
                    <li><a title="Video" href="" target="_blank">Video</a></li>
                </ul>
            </li>
        </ul>
        <ul class="bar-top-right">
            <li class="ktdh" id="ktdh"><a href="javascript:void(0)" class="" title="Kiểm tra đơn hàng">
                    <svg class="icon-Fcategory">
                        <use xlink:href="#icon-Fcategory"></use>
                    </svg>
                    Kiểm tra đơn hàng</a>
                <!--ktdh-->
                <div class="sub-bar-top sub-ktdh"></div>
                <!--ktdh-logged-->
                <!--  -->
            </li>
            <li class="hd"><a href="javascript:void(0);" title="Hướng dẫn">
                    <svg class="icon-question">
                        <use xlink:href="#icon-question"></use>
                    </svg>
                    Hướng dẫn</a>

                <div class="sub-bar-top sub-hd">
                    <a href="" title="Các câu hỏi thường gặp">Các câu hỏi thường gặp </a>
                    <a href="" title="Hướng dẫn mua hàng ">Hướng dẫn mua
                        hàng </a>
                    <a href="" title="Mua sắm thông minh">Mua sắm thông
                        minh</a>
                    <a href="" title="Mua hàng đảm bảo">Mua hàng đảm bảo</a> <a
                        href="" title="Cách thức thanh toán">Cách thức thanh
                        toán</a>
                    <a href="" title="Giao hàng toàn quốc">Giao hàng toàn
                        quốc</a>
                    <a href="" title="Shop hoa sen">Shop hoa sen</a> <a
                        href="" title="Về Sendo.vn">Về web.vn</a>
                </div>
            </li>
        </ul>
    </div>
</div>
<!--end block bar head module