<!--  start block bar head module -->
<div class="container-fluid bar-top" id="bartop">
    <div class="row">
        <div class="bar-top-cont">
            <ul class="bar-top-left">
                <li><a href="" title="Xu hướng">Xu hướng</a></li>
                <li><a href="<?php echo $this->view->url('productProperties',array('action' => 'san-pham-khuyen-mai','extension' => 'html'))?>" title="Khuyến mãi">Khuyến mãi</a></li>
                <li><a href="<?php echo $this->view->url('productProperties',array('action' => 'san-pham-ban-chay','extension' => 'html'))?>" title="Bán chạy">Bán chạy</a></li>
                <li>
                    <a class="tl" href="" title="Tin tức">Tin Tức</a>
                    <ul class="sub-blog">
                    <?php

                        $categories = $this->getListPostCategory();
                        foreach ($categories as $category)
                            echo '<li><a title="'. $category['name'] .'" href="'. $this->view->basePath() . '/tin-tuc/' . $category['alias'] . '-' . $category['id'] . '.html' .'">'. $category['name'] .'</a></li>';
                    ?>
                    </ul>
                </li>
            </ul>
            <ul class="bar-top-right">
                <li class="tlds"><a href="" title="Tích lũy điểm sen">Tích lũy điểm thưởng</a></li>
                <li class="hd"><a href="javascript:void(0);" title="Hướng dẫn">
                        <svg class="icon-question">
                            <use xlink:href="#icon-question"></use>
                        </svg>
                        Hướng dẫn</a>

                    <div class="sub-bar-top sub-hd">
                        <a href="" title="Các câu hỏi thường gặp">Các câu hỏi thường gặp </a>
                        <a href="" title="Hướng dẫn mua hàng ">Hướng dẫn mua
                            hàng </a>
                        <a href="" title="Mua sắm thông minh">Mua sắm thông
                            minh</a>
                        <a href="" title="Mua hàng đảm bảo">Mua hàng đảm bảo</a> <a
                            href="" title="Cách thức thanh toán">Cách thức thanh
                            toán</a>
                        <a href="" title="Giao hàng toàn quốc">Giao hàng toàn
                            quốc</a>
                        <a href="" title="Shop hoa sen">Shop hoa sen</a> <a
                            href="" title="Về Sendo.vn">Về web.vn</a>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>
<!--end block bar head module