<!--  start block bar head module -->
<div class="bar-top">
<div class="bar-top-cont">
<ul class="bar-top-left">
    <li><a href="" target="_blank" title="Xu hướng">Xu hướng</a></li>
    <li><a href="" target="_blank" title="Khuyến mãi">Khuyến mãi</a></li>
    <li><a href="" target="_blank" title="Bán chạy">Bán chạy</a></li>
    <li class="tlds"><a href="" target="_blank" title="Tích lũy điểm sen">Tích lũy điểm
            sen</a></li>
    <li>
        <a class="tl" href="" target="_blank" title="Nhịp sống">Nhịp sống</a>
        <ul class="sub-blog-sendo">
            <li><a title="Thời trang" href="" target="_blank">Thời trang</a>
            </li>
            <li><a title="Làm đẹp" href="" target="_blank">Làm đẹp</a></li>
            <li><a title="Gia đình" href="" target="_blank">Giải trí</a></li>
            <li><a title="Gia đình" href="" target="_blank">Gia đình</a></li>
            <li><a title="Cẩm nang" href="" target="_blank">Cẩm nang</a></li>
            <li><a title="Tin tức" href="" target="_blank">Tin tức
                    </a></li>
            <li><a title="Video" href="" target="_blank">Video</a></li>
        </ul>
    </li>

</ul>
<ul class="bar-top-right">
    <li class="ktdh" id="ktdh"><a href="javascript:void(0)" class="" title="Kiểm tra đơn hàng">
            <svg class="icon-Fcategory">
                <use xlink:href="#icon-Fcategory"></use>
            </svg>
            Kiểm tra đơn hàng</a>
        <!--ktdh-->
        <div class="sub-bar-top sub-ktdh"></div>
        <!--ktdh-logged-->
        <!--  -->
    </li>
    <li class="hd"><a href="javascript:void(0);" title="Hướng dẫn">
            <svg class="icon-question">
                <use xlink:href="#icon-question"></use>
            </svg>
            Hướng dẫn</a>

        <div class="sub-bar-top sub-hd">
            <a href="" title="Các câu hỏi thường gặp">Các câu hỏi thường gặp </a>
            <a href="" title="Hướng dẫn mua hàng ">Hướng dẫn mua
                hàng </a>
            <a href="" title="Mua sắm thông minh">Mua sắm thông
                minh</a>
            <a href="" title="Mua hàng đảm bảo">Mua hàng đảm bảo</a> <a
                href="" title="Cách thức thanh toán">Cách thức thanh
                toán</a>
            <a href="" title="Giao hàng toàn quốc">Giao hàng toàn
                quốc</a>
            <a href="" title="Shop hoa sen">Shop hoa sen</a> <a
                href="" title="Về Sendo.vn">Về web.vn</a>
        </div>
    </li>
</ul>
</div>
</div>
<!--end block bar head module