    <!-- mobile menu close -->
<div class="td-mobile-close">
    <a href="#">CLOSE</a>
    <div class="td-nav-triangle"></div>
</div>

<div class="td-mobile-content">
    <div class="menu-td-header-container"><ul id="menu-td-header" class=""><li id="menu-item-655" class="menu-item menu-item-type-post_type menu-item-object-page current-menu-item page_item page-item-25 current_page_item menu-item-first td-no-down-arrow menu-item-655"><a href="http://whatshot.vn/"><span class="menu_icon td-sp td-sp-ico-home"></span><span class="menu_hidden">Home</span></a></li>
            <li id="menu-item-85" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-85"><a href="http://whatshot.vn/hot/">HOT</a></li>
            <li id="menu-item-89" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-89"><a href="http://whatshot.vn/sao/">SAO</a></li>
            <li id="menu-item-88" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-88"><a href="http://whatshot.vn/videos/">VIDEOS</a></li>
            <li id="menu-item-96" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-96"><a href="http://whatshot.vn/the-thao/">THỂ THAO</a></li>
            <li id="menu-item-98" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-98"><a href="http://whatshot.vn/lam-dep/">ĐẸP</a></li>
            <li id="menu-item-97" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-97"><a href="http://whatshot.vn/yeu-duc/">YÊU – DỤC</a></li>
            <li id="menu-item-90" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-90"><a href="http://whatshot.vn/an-uong/">ĂN UỐNG</a></li>
            <li id="menu-item-92" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-92"><a href="http://whatshot.vn/nhac/">NHẠC</a></li>
            <li id="menu-item-94" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-94"><a href="http://whatshot.vn/thoi-trang/">THỜI TRANG</a></li>
            <li id="menu-item-99" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-99"><a href="http://whatshot.vn/hoc/">HỌC</a></li>
            <li id="menu-item-14" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children td-no-down-arrow menu-item-14"><a href="#"><span class="menu_icon td-sp td-sp-ico-categ"></span><span class="menu_hidden">Categories</span></a>
                <ul class="sub-menu">
                    <li id="menu-item-127" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-127"><a href="http://whatshot.vn/mang-thai/">Mang thai</a></li>
                    <li id="menu-item-128" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-128"><a href="http://whatshot.vn/noi-bat/">Nổi bật</a></li>
                    <li id="menu-item-126" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-126"><a href="http://whatshot.vn/lam-cha-me/">Làm cha mẹ</a></li>
                    <li id="menu-item-125" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-125"><a href="http://whatshot.vn/kinh-doanh/">Kinh doanh</a></li>
                    <li id="menu-item-124" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-124"><a href="http://whatshot.vn/du_lich/">Du lịch</a></li>
                    <li id="menu-item-123" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-123"><a href="http://whatshot.vn/cong-nghe/">Công nghệ</a></li>
                    <li id="menu-item-122" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-122"><a href="http://whatshot.vn/chinh-tri/">Chính trị</a></li>
                    <li id="menu-item-651" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-651"><a href="http://whatshot.vn/suc-khoe/">Khỏe</a></li>
                    <li id="menu-item-776" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-776"><a href="http://whatshot.vn/phim-anh/">Phim ảnh</a></li>
                </ul>
            </li>
        </ul>
    </div>
</div>