<div class="container-fluid">
    <div class="row">
    </div>
    <div class="row">
        <!-- left col -->
        <div class="col-left">
            <div class="filter-list">
                <?php echo $this->menuCategories() ?>
            </div>
        </div>
        <div class="col-right">
            <div id="products-listing-filter-load">
                <div class="products-listing util-clearfix">
                    <div class="row">
                        <?php echo $this->partial('home/list-products.phtml',array('products' => $this->products))?>
                    </div>
                </div>
            </div>
            <div class="bg-load-ajax"><img src="<?php echo $this->basePath()?>/public/template/frontend/images/load.gif" alt=""></div>
        </div>
    </div>

    <div class="hide">
        <input type="hidden" value="<?php echo $this->category->id ?>" id="category-id">
    </div>

    <?php echo $this->miniBarMenu()?>
</div>
