<div class="container-fluid">
    <div class="row">
        <div class="top-content">
            <div class="breadcrumb_detail util-clearfix">
                <div class="br first">
                    <a href="<?php echo $this->url('home') ?>">
                        <span>Trang Chủ</span> </a>
                </div>
                <div class="br-end link">
                    <a href="" title="">
                        <span><?php echo $this->title ?></span>
                    </a>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="block  category-header" id="block-main-category-header">
            <div class="block__header  ">
                <h1 class="block__title category-header-heading">
                    <?php echo $this->title ?>
                </h1>
            </div>
        </div>
    </div>
    <div class="row">
        <!-- left col -->
        <div class="col-right">
            <div id="products-listing-filter-load">
                <div class="products-listing util-clearfix">
                    <div class="row">
                        <?php echo $this->partial('home/list-products.phtml',array('products' => $this->products))?>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="hide">
        <input type="hidden" value="<?php echo $this->category->id ?>" id="category-id">
    </div>

    <?php echo $this->miniBarMenu()?>
</div>
<div class="bg-load-ajax hidden">
    <div class="wrapper-contend">
        <img src="<?php echo $this->basePath()?>/public/template/frontend/images/load-more.gif" alt="">
        <div class="span">Vui lòng chờ load thêm sản phẩm</div>
    </div>
</div>
<input type="hidden" id="action" value="<?php echo $this->action   ?>">