<div class="container-wrap -page">
	<div id="jsMenuMarkLayer">&nbsp;</div>
	<div id="content">
		<!--profile-follow-product-->
		<div class="container">
			<div class="wrapper-profile profile-user-account">
				<?php echo $this->leftProfileUser('payment-orders') ?>
				<!--right-profile-->
				<div class="right-profile">
					<div class="ttl-box-profile">Danh sách đơn hàng đã thanh toán</div>
					<div class="article">
						<div class="icons">
							<table width="100%" class="yourCart" id="yourCart774">
								<tbody>
									<tr>
										<th>Thứ tự</th>
										<th>Mã Hóa Đơn</th>
										<th>Tổng Sản Phẩm</th>
										<th>Tổng Giá Trị</th>
										<th>Trạng Thái </th>
										<th>Thời Gian đặt hàng</th>
									</tr>
									<?php 
									foreach ($danhSachHoaDon as $key => $hoadon) {
										echo '<tr>
												<td>'. ($key + 1) .'</td>
												<td>'. $hoadon->code .'</td>
												<td>'. $hoadon->total_product .'</td>
												<td>'. number_format($hoadon->total_money,0,',','.') .'</td>
												<td>'. $hoadon->statusOrder .'</td>
												<td>'. date("d/m/Y G.i:s",strtotime($hoadon->time_order)) .'</td>
											</tr>';
									}

									?>
							</tbody></table>
						<div style="clear:both"></div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
</div>