<div class="container-wrap -page">
	<div id="jsMenuMarkLayer">&nbsp;</div>
	<div id="content">
		<!--profile-follow-product-->
		<div class="container">
			<div class="wrapper-profile profile-user-account">
				<?php echo $this->leftProfileUser('payment-orders') ?>
				<!--right-profile-->
				<div class="right-profile">
					<div class="ttl-box-profile">Danh sách đơn hàng đã thanh toán</div>
					<div class="article">
						<div class="icons">
							<table width="100%" class="yourCart" id="yourCart774">
								<tbody>
									<tr>
										<th>Thứ tự</th>
										<th>Tên sản phẩm </th>
										<th>Mã SP</th>
										<th>Hình SP </th>
										<th>Size</th>
										<th>Giá bán</th>
										<th>Số lượng </th>
										<th>Thành tiền </th>
									</tr>
									<tr id="892">
										<td>1</td>
										<td>
											<a href="/goi-cao-su-cao-cap-wean-12x42x62-892.html">Đầm Váy Công Sỏ</a>
										</td>
										<td>GCCW</td>
									<td>
										<img src="<?php echo $this->basePath('public/files/product/100x100/product_AcLvqpyg.jpg') ?>">
									</td>
									<td class="size">mặc định</td>
									<td class="price-892">462,000</td>
									<td>
										<label for="select">
											<input name="number" class="number" id="number-892" data-id="892" type="text" value="1">
										</label>
									</td>
									<td class="total-amount-892">462,000 </td>
								</tr>
							</tbody></table>
							<table width="100%" id="pannel" class="yourCart">
								<tbody>
								<tr>
									<td class="noborderTop" width="450">
										<a class="toltall">Tổng  tiền: <span id="tonggia" style="color:#CD0A0A">462,000 VNĐ</span>
										</a>
									</td>
								</tr>
							</tbody>
						</table>
						<div style="clear:both"></div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
</div>