<?php
$arr = [
        ['title' => 'Kích thước'],
        ['title' => 'trạng thái'],
        ['title' => 'chức năng'],
        ['title' => 'id'],
    ];
?>

<div class="row">
    <div class="col-lg-6">
        <div class="panel " id="meta_fieldset_general">
            <div class="panel-heading">
                <i class="fa fa-info-circle"></i>
                Kích thước sản phẩm
                <div class="btnfunction">
                    <i class="fa fa-search"></i>
                    <i class="fa fa-plus-circle"></i>
                    <i class="fa fa-trash-o"></i>
                    <i class="fa fa-check"></i>
                    <i class="fa fa-times"></i>
                </div>
            </div>
            <div class="panel-content">
                <?php echo $this->datatable('size', $arr);?>
            </div>
        </div>
    </div>
</div>