<div class="modal fade buy-success" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      	<div class="content">
      		<p>Đặt Hàng Thành Công</p>
      		<p>Cám ơn bạn đã đặt mua hàng tại Webseo. Chúng tôi sẽ liên hệ và giao hàng trong 3 ngày</p>
      		<p>Bạn Có thể tra cứu mã đơn đặt hàng <strong></strong> để biết trạng thái xử lý.</p>
      		<img src="<?php echo $this->view->basePath('public/template/frontend/images/buy-success.png')?>" alt="buy sucess">
      		<p class="home">Quay về trang chủ</p>
      		<p>Tự động chuyển đến trang chủ sau <b class="s">5</b> giây nữa</p>
      	</div>
    </div>
  </div>
</div>