<header class="page-header">
    <h1 class="page-title" style="border-bottom-color: #bd4cce">
        <span style="background-color: #bd4cce">Fashion</span>
    </h1>
</header>

<div class="article-container">
    <article class="post type-post status-publish format-standard has-post-thumbnail hentry category-fashion category-female category-style">
        <div class="featured-image">
            <a href="#" title="">
                <img width="800" height="445" src="http://demo.themegrill.com/colormag/wp-content/uploads/sites/20/2015/03/model-600225_1280-800x445.jpg"
                                                         class="attachment-colormag-featured-image size-colormag-featured-image wp-post-image"
                                                         alt="model-600225_1280">
            </a>
        </div>

        <div class="article-content clearfix">
            <div class="above-entry-meta">
                <span class="cat-links">
                    <a href="#" style="background:#bd4cce">Fashion</a>&nbsp;
                    <a href="#" style="background:#d8a0c2">Female</a>&nbsp;
                    <a href="#" style="background:#b17fe2">Style</a>&nbsp;
                </span>
            </div>
            <header class="entry-header">
                <h2 class="entry-title">
                    <a href="#" title="Looks from the Roswana, 2015">Looks from the Roswana, 2015</a>
                </h2>
            </header>
            <div class="below-entry-meta">
                <span class="posted-on">
                    <a href="#" title="6:31 am" rel="bookmark"><i class="fa fa-calendar-o"></i>
                        <time class="entry-date published" datetime="2015-03-24T06:31:54+00:00">March 24, 2015</time>
                        <time class="updated" datetime="2015-06-22T09:59:14+00:00">June 22, 2015</time>
                    </a>
                </span>
                <span class="byline">
                    <span class="author vcard">
                        <i class="fa fa-user"></i>
                        <a class="url fn n" href="#" title="TG-Demo Team">TG-Demo Team</a>
                    </span>
                </span>
            </div>
            <div class="entry-content clearfix">
                <p>For Joesendra, this is only her second fashion week showing, following her presentation at a Fashion
                    World on this January.</p>
                <a class="more-link" title="Looks from the Roswana, 2015"
                   href="#"><span>Read more</span></a>
            </div>
        </div>

    </article>

    <article id="post-66"
             class="post-66 post type-post status-publish format-standard has-post-thumbnail hentry category-fashion category-general">

        <div class="featured-image">
            <a href="http://demo.themegrill.com/colormag/2015/03/24/color-your-hair-3/" title="Color your Hair"><img
                    width="800" height="445"
                    src="http://demo.themegrill.com/colormag/wp-content/uploads/sites/20/2015/03/beauty-666605_1920-800x445.jpg"
                    class="attachment-colormag-featured-image size-colormag-featured-image wp-post-image"
                    alt="beauty-666605_1920"></a>
        </div>

        <div class="article-content clearfix">


            <div class="above-entry-meta"><span class="cat-links"><a
                        href="http://demo.themegrill.com/colormag/category/fashion/" style="background:#bd4cce"
                        rel="category tag">Fashion</a>&nbsp;<a
                        href="http://demo.themegrill.com/colormag/category/general/" style="background:#a38a6d"
                        rel="category tag">General</a>&nbsp;</span></div>
            <header class="entry-header">
                <h2 class="entry-title">
                    <a href="http://demo.themegrill.com/colormag/2015/03/24/color-your-hair-3/" title="Color your Hair">Color
                        your Hair</a>
                </h2>
            </header>

            <div class="below-entry-meta">
                <span class="posted-on"><a href="http://demo.themegrill.com/colormag/2015/03/24/color-your-hair-3/"
                                           title="6:27 am" rel="bookmark"><i class="fa fa-calendar-o"></i>
                        <time class="entry-date published" datetime="2015-03-24T06:27:32+00:00">March 24, 2015</time>
                        <time class="updated" datetime="2015-03-25T07:05:13+00:00">March 25, 2015</time>
                    </a></span>
                <span class="byline"><span class="author vcard"><i class="fa fa-user"></i><a class="url fn n"
                                                                                             href="http://demo.themegrill.com/colormag/author/demothemegrill/"
                                                                                             title="TG-Demo Team">TG-Demo
                            Team</a></span></span>

            </div>
            <div class="entry-content clearfix">
                <p>Bear claw cake cake apple pie candy muffin. Dessert croissant soufflé cheesecake dessert croissant
                    dragée candy canes candy canes. Wafer</p>
                <a class="more-link" title="Color your Hair"
                   href="http://demo.themegrill.com/colormag/2015/03/24/color-your-hair-3/"><span>Read more</span></a>
            </div>

        </div>

    </article>


    <article id="post-63"
             class="post-63 post type-post status-publish format-standard has-post-thumbnail hentry category-fashion category-news category-style">

        <div class="featured-image">
            <a href="http://demo.themegrill.com/colormag/2015/03/24/new-styling-collections/"
               title="New Styling Collections"><img width="800" height="445"
                                                    src="http://demo.themegrill.com/colormag/wp-content/uploads/sites/20/2015/03/window-213496_1280-800x445.jpg"
                                                    class="attachment-colormag-featured-image size-colormag-featured-image wp-post-image"
                                                    alt="window-213496_1280"></a>
        </div>

        <div class="article-content clearfix">


            <div class="above-entry-meta"><span class="cat-links"><a
                        href="http://demo.themegrill.com/colormag/category/fashion/" style="background:#bd4cce"
                        rel="category tag">Fashion</a>&nbsp;<a href="http://demo.themegrill.com/colormag/category/news/"
                                                               style="background:#bfd6af" rel="category tag">News</a>&nbsp;<a
                        href="http://demo.themegrill.com/colormag/category/style/" style="background:#b17fe2"
                        rel="category tag">Style</a>&nbsp;</span></div>
            <header class="entry-header">
                <h2 class="entry-title">
                    <a href="http://demo.themegrill.com/colormag/2015/03/24/new-styling-collections/"
                       title="New Styling Collections">New Styling Collections</a>
                </h2>
            </header>

            <div class="below-entry-meta">
                <span class="posted-on"><a
                        href="http://demo.themegrill.com/colormag/2015/03/24/new-styling-collections/" title="6:25 am"
                        rel="bookmark"><i class="fa fa-calendar-o"></i>
                        <time class="entry-date published" datetime="2015-03-24T06:25:39+00:00">March 24, 2015</time>
                        <time class="updated" datetime="2015-06-22T10:01:22+00:00">June 22, 2015</time>
                    </a></span>
                <span class="byline"><span class="author vcard"><i class="fa fa-user"></i><a class="url fn n"
                                                                                             href="http://demo.themegrill.com/colormag/author/demothemegrill/"
                                                                                             title="TG-Demo Team">TG-Demo
                            Team</a></span></span>

            </div>
            <div class="entry-content clearfix">
                <p>Phasellus at ligula consequat purus dignissim sodales non ac nisi. Vestibulum vehicula erat in purus
                    vestibulum facilisis. Lorem ipsum dolor</p>
                <a class="more-link" title="New Styling Collections"
                   href="http://demo.themegrill.com/colormag/2015/03/24/new-styling-collections/"><span>Read more</span></a>
            </div>

        </div>

    </article>


    <article id="post-60"
             class="post-60 post type-post status-publish format-standard has-post-thumbnail hentry category-fashion">

        <div class="featured-image">
            <a href="http://demo.themegrill.com/colormag/2015/03/24/consectetur-adipiscing/"
               title="Consectetur adipiscing"><img width="800" height="445"
                                                   src="http://demo.themegrill.com/colormag/wp-content/uploads/sites/20/2015/03/relaxed-498245_1280-800x445.jpg"
                                                   class="attachment-colormag-featured-image size-colormag-featured-image wp-post-image"
                                                   alt="relaxed-498245_1280"></a>
        </div>

        <div class="article-content clearfix">


            <div class="above-entry-meta"><span class="cat-links"><a
                        href="http://demo.themegrill.com/colormag/category/fashion/" style="background:#bd4cce"
                        rel="category tag">Fashion</a>&nbsp;</span></div>
            <header class="entry-header">
                <h2 class="entry-title">
                    <a href="http://demo.themegrill.com/colormag/2015/03/24/consectetur-adipiscing/"
                       title="Consectetur adipiscing">Consectetur adipiscing</a>
                </h2>
            </header>

            <div class="below-entry-meta">
                <span class="posted-on"><a href="http://demo.themegrill.com/colormag/2015/03/24/consectetur-adipiscing/"
                                           title="6:22 am" rel="bookmark"><i class="fa fa-calendar-o"></i>
                        <time class="entry-date published" datetime="2015-03-24T06:22:35+00:00">March 24, 2015</time>
                        <time class="updated" datetime="2015-03-24T06:23:43+00:00">March 24, 2015</time>
                    </a></span>
                <span class="byline"><span class="author vcard"><i class="fa fa-user"></i><a class="url fn n"
                                                                                             href="http://demo.themegrill.com/colormag/author/demothemegrill/"
                                                                                             title="TG-Demo Team">TG-Demo
                            Team</a></span></span>

            </div>
            <div class="entry-content clearfix">
                <p>Consectetur adipiscing elit. Aenean lectus nisi, convallis a tortor vitae, congue luctus velit.
                    Vivamus faucibus massa non ultrices molestie. Aliquam</p>
                <a class="more-link" title="Consectetur adipiscing"
                   href="http://demo.themegrill.com/colormag/2015/03/24/consectetur-adipiscing/"><span>Read more</span></a>
            </div>

        </div>

    </article>


    <article id="post-172"
             class="post-172 post type-post status-publish format-standard has-post-thumbnail hentry category-fashion">

        <div class="featured-image">
            <a href="http://demo.themegrill.com/colormag/2015/03/24/lacus-ultricies/" title="Lacus Ultricies"><img
                    width="800" height="445"
                    src="http://demo.themegrill.com/colormag/wp-content/uploads/sites/20/2015/03/girl-237871_1280-800x445.jpg"
                    class="attachment-colormag-featured-image size-colormag-featured-image wp-post-image"
                    alt="girl-237871_1280"></a>
        </div>

        <div class="article-content clearfix">


            <div class="above-entry-meta"><span class="cat-links"><a
                        href="http://demo.themegrill.com/colormag/category/fashion/" style="background:#bd4cce"
                        rel="category tag">Fashion</a>&nbsp;</span></div>
            <header class="entry-header">
                <h2 class="entry-title">
                    <a href="http://demo.themegrill.com/colormag/2015/03/24/lacus-ultricies/" title="Lacus Ultricies">Lacus
                        Ultricies</a>
                </h2>
            </header>

            <div class="below-entry-meta">
                <span class="posted-on"><a href="http://demo.themegrill.com/colormag/2015/03/24/lacus-ultricies/"
                                           title="6:07 am" rel="bookmark"><i class="fa fa-calendar-o"></i>
                        <time class="entry-date published" datetime="2015-03-24T06:07:07+00:00">March 24, 2015</time>
                        <time class="updated" datetime="2015-03-25T08:09:30+00:00">March 25, 2015</time>
                    </a></span>
                <span class="byline"><span class="author vcard"><i class="fa fa-user"></i><a class="url fn n"
                                                                                             href="http://demo.themegrill.com/colormag/author/demothemegrill/"
                                                                                             title="TG-Demo Team">TG-Demo
                            Team</a></span></span>

            </div>
            <div class="entry-content clearfix">
                <p>Donec sed justo efficitur, pulvinar elit in, dignissim nibh. Nulla porttitor tortor et mi auctor
                    condimentum. Aliquam sodales ac quam</p>
                <a class="more-link" title="Lacus Ultricies"
                   href="http://demo.themegrill.com/colormag/2015/03/24/lacus-ultricies/"><span>Read more</span></a>
            </div>

        </div>

    </article>


    <article id="post-53"
             class="post-53 post type-post status-publish format-standard has-post-thumbnail hentry category-entertainment category-fashion category-featured category-sports">

        <div class="featured-image">
            <a href="http://demo.themegrill.com/colormag/2015/03/19/tennis-match-go-federer/"
               title="Tennis Match: Go Federer"><img width="800" height="445"
                                                     src="http://demo.themegrill.com/colormag/wp-content/uploads/sites/20/2015/03/clouds-sky-stadium-4516-800x445.jpg"
                                                     class="attachment-colormag-featured-image size-colormag-featured-image wp-post-image"
                                                     alt="DCIM100GOPRO"></a>
        </div>

        <div class="article-content clearfix">


            <div class="above-entry-meta"><span class="cat-links"><a
                        href="http://demo.themegrill.com/colormag/category/entertainment/" style="background:#e8357c"
                        rel="category tag">Entertainment</a>&nbsp;<a
                        href="http://demo.themegrill.com/colormag/category/fashion/" style="background:#bd4cce"
                        rel="category tag">Fashion</a>&nbsp;<a
                        href="http://demo.themegrill.com/colormag/category/featured/" style="background:#a4c4be"
                        rel="category tag">FEATURED</a>&nbsp;<a
                        href="http://demo.themegrill.com/colormag/category/sports/" style="background:#dd5a5a"
                        rel="category tag">Sports</a>&nbsp;</span></div>
            <header class="entry-header">
                <h2 class="entry-title">
                    <a href="http://demo.themegrill.com/colormag/2015/03/19/tennis-match-go-federer/"
                       title="Tennis Match: Go Federer">Tennis Match: Go Federer</a>
                </h2>
            </header>

            <div class="below-entry-meta">
                <span class="posted-on"><a
                        href="http://demo.themegrill.com/colormag/2015/03/19/tennis-match-go-federer/" title="3:53 pm"
                        rel="bookmark"><i class="fa fa-calendar-o"></i>
                        <time class="entry-date published" datetime="2015-03-19T15:53:24+00:00">March 19, 2015</time>
                        <time class="updated" datetime="2015-06-22T09:52:51+00:00">June 22, 2015</time>
                    </a></span>
                <span class="byline"><span class="author vcard"><i class="fa fa-user"></i><a class="url fn n"
                                                                                             href="http://demo.themegrill.com/colormag/author/demothemegrill/"
                                                                                             title="TG-Demo Team">TG-Demo
                            Team</a></span></span>

            </div>
            <div class="entry-content clearfix">
                <p>Sesame snaps cookie oat cake jelly cheesecake dragée cake marzipan sesame snaps. Muffin soufflé donut
                    lollipop tootsie roll. Tart donut</p>
                <a class="more-link" title="Tennis Match: Go Federer"
                   href="http://demo.themegrill.com/colormag/2015/03/19/tennis-match-go-federer/"><span>Read more</span></a>
            </div>

        </div>

    </article>

</div>