<!--start block hot deal product module-->
<div class="good-deal saq-good-deal1" id="hot-deal-products">
    <div class="title-deal">
        <a id="saq-deal-href" title="Deal tốt, HỐT LUÔN!" href="#" class="tl">Deal tốt, HỐT LUÔN!</a>
    </div>
    <div class="box-2-deal">
        <a class="deal-item deal01" href="<?php echo $this->view->basePath('ao-khoac-han-quoc-cao-cap-53.html') ?>"
           title="Áo khoác hàn quốc cao cấp">
            <img src="<?php echo $this->view->basePath('public/files/product/203x235/product_7A5mZxHS.jpg') ?>" title=""
                 alt="Áo khoác hàn quốc cao cấp"/>
            <div class="box-name">
		        <span class="deal-price">
                    <span class="deal-price-n">500,000 VNĐ</span>
                    <span class="deal-price-o">250,000 VNĐ</span>
                </span>
                <div class="name">Áo khoác hàn quốc cao cấp</div>
            </div>
            <div class="discout">-50%</div>
        </a>
        <a class="deal-item deal02" href="<?php echo $this->view->basePath('ao-nu-thoi-trang-63.html') ?>"
           title="Pin sạc dự phòng SAMSUNG 25000mAh">
            <img src="<?php echo $this->view->basePath('public/files/product/203x235/product_ZInxjVet.jpg') ?>" title=""
                 alt="Pin sạc dự phòng SAMSUNG 25000mAh"/>
            <div class="box-name">
		                <span class="deal-price">
		                    <span class="deal-price-n">320.000 VNĐ</span>
                            <span class="deal-price-o">310.000 VNĐ</span>
                        </span>
                <div class="name">Buffet Chooki BBQ & Hotpot</div>
            </div>
            <div class="discout">-50%</div>
        </a>
    </div>
</div>
<!--end block product deal module-->