<div class="modal fade buy-now">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <div class="ppu_header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                    <p class="ppu_h_title">ĐẶT HÀNG - NGHE TƯ VẤN MIỄN PHÍ</p>
                    <p class="ppu_h_noti">(Không mua không sao)</p>
                </div>
            </div>
            <div class="modal-body">
                <div class="ppu_tabs_main">
                    <!-- clear html when click list maps, changer to div.ppu_ss_main -->
                    <!-- #1 TAB HOME-->
                    <div class="ppu_content" id="ppu-tab-home">
                        <div class="ppu_tab_content clearfix">
                            <!-- LEFT TAB-->
                            <div class="ppu_tab_left">
                                <div class="ppu_tab_left_content">
                                    <div class="clearfix">
                                        <div class="ppu_tab_proimg"></div>

                                        <div class="ppu_tab_pro_info">
                                            <div class="ppu_tab_pro_name"></div>
                                            <div class="lineprice" id="price"></div>
                                            <div class="info" id="sizeName"></div>
                                            <div class="info" id="quantity"></div>
                                            <div class="info" id="totalMoney"></div>
                                            <div class="info" id="point">Điểm tích lũy: Hãy đăng nhập để tích lũy điểm</div>
                                        </div>
                                        <div class="clearfix"></div>
                                    </div>
                                </div>
                            </div>
                            <!-- RIGHT TAB-->
                            <div class="ppu_tab_right">
                                <div class="ppu_tab_right_box">
                                    <span style="color:red">(*) Bạn buộc phải nhập thông tin vào!</span>
                                    <?php if($this->view->identity()){?>
                                    <p class="pform-inline">
                                        <input name="full_name" class="ppu_rtxt form-control" type="text" placeholder="Họ tên bạn" value="<?php echo $this->view->identity()->username ?>" disabled="disabled">
                                        <i>*</i>
                                    </p>
                                    <p class="pform-inline">
                                        <input name="phone" class="ppu_rtxt form-control" type="text" placeholder="Số điện thoại" value="<?php echo $this->view->identity()->phone ?>" disabled="disabled">
                                        <i>*</i>
                                    </p>
                                    <p class="pform-inline">
                                        <input type="text" name="email" id="email" class="form-control" placeholder="Địa chỉ email" value="<?php echo $this->view->identity()->email ?>" disabled="disabled">
                                        <i>*</i>
                                    </p>
                                    <?php }else{?>
                                    <p class="pform-inline">
                                        <input name="full_name" class="ppu_rtxt form-control" type="text" placeholder="Họ tên bạn">
                                        <i>*</i>
                                    </p>
                                    <p class="pform-inline">
                                        <input name="phone" class="ppu_rtxt form-control" type="text" placeholder="Số điện thoại">
                                        <i>*</i>
                                    </p>
                                    <p class="pform-inline">
                                        <input type="text" id="email" name="email" class="form-control" placeholder="Địa chỉ email">
                                        <i>*</i>
                                    </p>
                                    <?php } ?>
                                    <p class="pform-inline" style="display:none">
                                        <input type="text" id="address" name="address" class="form-control" placeholder="Địa chỉ giao hàng"><i>*</i>
                                    </p>
                                    <textarea name="note" id="note" class="form-control" placeholder="Ghi Chú"></textarea>
                                    <button class="ppu_rbnt_submit"> Đặt Ngay</button>
                                </div>
                            </div>
                        </div>
                        <div class="hidden-input">
                            <input type="hidden" name="address" id="shipping-address">
                        </div>
                        <!-- BOTTOM TAB-->
                        <div class="ppu_bottom_noti">
                            <p>Chúng tôi sẽ liên hệ với bạn trong vòng <strong>1 tiếng</strong>  và cam kết giao hàng miễn phí trong <strong>1 ngày</strong>.</p>
                            <p class="ppu_bt_call">Tư vấn &amp; chăm sóc khách hàng: <strong>1900.555.559</strong></p>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>