<?php
    $linkImage = $this->basePath('public/template/landing-page/images/');
?>
<section id="header">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-1" id="menu">
                <div class="icon-open-menu">
                    <i class="fa fa-bars"></i>
                </div>
                <div class="icon-close-menu">
                    <i class="fa fa-times"></i>
                </div>
            </div>
            <div class="list-menu">
                <ul>
                    <li>
                        <span>Home</span>
                    </li>
                    <li>
                        <div class="icon-distance first">
                            <img src="<?php echo $linkImage?>gach-xeo.png" alt="gach-xeo">
                        </div>
                        <span>Project Collection</span>
                        <div class="icon-distance last">
                            <img src="<?php echo $linkImage?>gach-xeo.png" alt="gach-xeo">
                        </div>
                    </li>
                    <li>About Us</li>
                </ul>
            </div>
            <div class="col-sm-10" id="logo">
                <div class="logo-image">
                    <a href="<?php echo $this->serverUrl() ?>" class="banner-img">
                        <img src="<?php echo $linkImage?>logo-header.png" alt="Minh Chuong">
                    </a>
                </div>
            </div>
            <div class="col-sm-1" id="social">
                <div class="logo-image">
                    <a href="">
                        <img src="<?php echo $linkImage?>icon-fb.png" alt="Minh Chuong">
                    </a>
                </div>
            </div>
        </div>
    </div>
</section>

<section id="slideshow">
    <div class="container">
        <div class="row">
            <div id="banner-slide">
                <ul class="bjqs">
                    <li>
                        <img src="<?php echo $linkImage?>slide1.png" title="<span class='title'>CONTRUCTION</span><br><span class='description'>PROJECTTYPE INTERIOR MANUFACTURING * LOCATION MEKONG DETA VIETNAM</span><span class='readmore'><a href='#'>Readmore</a></span>">
                    </li>
                    <li>
                        <img src="<?php echo $linkImage?>slide2.png" title="<span class='title'>INTERIOR</span><br><span class='description'>PROJECTTYPE INTERIOR MANUFACTURING * LOCATION MEKONG DETA VIETNAM</span><span class='readmore'><a href='#'>Readmore</a></span>">
                    </li>
                    <li>
                        <img src="<?php echo $linkImage?>slide3.png" title="<span class='title'>FUNITURE</span><br><span class='description'>PROJECTTYPE INTERIOR MANUFACTURING * LOCATION MEKONG DETA VIETNAM</span><span class='readmore'><a href='#'>Readmore</a></span>">
                    </li>
                </ul>
            </div>
            <div class="arrow container">
                <div class="row">
                    <div class="all-project col-sm-4">
                        <div class="des"><span>View ALL Projects</span></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section id="home">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-6 slide-image" id="introduce">
                <div class="effect-line">&nbsp;</div>
                <div class="introduce-manu">
                    <div class="title">A Rich History of <br>craftsmanship & responsibility</div>
                    <div class="content">
                        <div class="border">border</div>
                        <div class="description">
                            <span>Width over 20 years of experience in  ahrchitecture and construction,
                                Minh Chuong has contributed excellent works in several projects in Ho Chi Minh city,
                                including FV Hospital, RMIT international University, Castrol BP, or HBP office.
                                During 22 year growing up with a large amount of clients, Minh Chuong has also spreaded
                                interior services for restautants and luxury resorts all over VietName
                            </span>
                            <div class="more">
                                Learn more
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 em-box-info">
                <a href="">
                    <img src="<?php echo $linkImage?>ads02.png" alt="advertise">
                </a>
            </div>
        </div>
    </div>
</section>

<section id="middle-home">
    <div class="container">
        <div class="row">
            <div class="block-service">
                <div class="title">
                    Industry-leading clients need top-quaility services
                </div>
                <hr>
                <div class="description">
                    At MINH CHUONG, we are accustomed to serving the best of clients.
                    The ones who require no less than the best services to fulfill the most
                    important of business objectives.
                </div>
                <div class="list-service">
                    <div class="row">
                        <div class="col-sm-4">
                            <div class="item">
                                <div class="item-hover circle">
                                    <div class="image img">
                                        <a href="">
                                            <img src="<?php echo $linkImage ?>3.png" alt="">
                                        </a>
                                    </div>
                                    <div class="info">
                                        <div class="info-back">
                                            <h3>View</h3>
                                            <p>All Contruction</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="title">Contruction</div>
                            <hr>
                            <div class="description">
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ligula nisl, egestas sagitis lectus ac.
                            </div>
                        </div>

                        <div class="col-sm-4">
                            <div class="item">
                                <div class="item-hover circle">
                                    <div class="image img">
                                        <a href="">
                                            <img src="<?php echo $linkImage ?>4.png" alt="">
                                        </a>
                                    </div>
                                    <div class="info">
                                        <div class="info-back">
                                            <h3>View</h3>
                                            <p>All Interior</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="title">Interior</div>
                            <hr>
                            <div class="description">
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ligula nisl, egestas sagitis lectus ac.
                            </div>
                        </div>
                        <div class="col-sm-4">
                            <div class="item">
                                <div class="item-hover circle">
                                    <div class="image img">
                                        <a href="">
                                            <img src="<?php echo $linkImage ?>5.png" alt="">
                                        </a>
                                    </div>
                                    <div class="info">
                                        <div class="info-back">
                                            <h3>View</h3>
                                            <p>All Furniture</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="title">Furniture</div>
                            <hr>
                            <div class="description">
                                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ligula nisl, egestas sagitis lectus ac.
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section id="bottom-home">
    <div class="container">
        <div class="row">
            <div class="block-manufacturer">
                <div class="title">NOTABLE CLIENTS</div>
                <hr>
                <ul class="list-logo">
                    <li>
                        <a href="#">
                            <img src="<?php echo $linkImage?>logo1.png" alt="">
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <img src="<?php echo $linkImage?>logo2.png" alt="">
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <img src="<?php echo $linkImage?>logo3.png" alt="">
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <img src="<?php echo $linkImage?>logo4.png" alt="">
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <img src="<?php echo $linkImage?>logo5.png" alt="">
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <img src="<?php echo $linkImage?>logo6.png" alt="">
                        </a>
                    </li>
                </ul>
                <div class="description">and more...</div>
            </div>
        </div>
    </div>
</section>

<section id="footer">
    <div class="container">
        <div class="row">
            <div class="col-sm-5">
                <div class="block-message">
                    <div class="title">Have a Question?</div>
                    <hr>
                    <div class="content">
                        <div class="control-group">
                            <label for="name" class="col-xs-4 control-label" style="margin-left: -20px">Name</label>
                            <input type="text" class="from-control input-large-text" name="username" id="username">
                        </div>
                        <div class="control-group">
                            <label for="email" class="col-xs-4 control-label" style="margin-left: -20px">Email</label>
                            <input type="text" class="from-control input-large-text" name="email" id="email">
                        </div>
                        <div class="control-group">
                            <label for="subject" class="col-xs-4 control-label" style="margin-left: -20px">Subject</label>
                            <input type="text" class="from-control input-large-text" name="subject" id="subject">
                        </div>
                        <div class="control-group">
                            <label for="message" class="col-xs-4 control-label" style="margin-left: -20px">Message</label>
                            <input type="text" class="from-control input-large-text" name="message" id="message">
                        </div>
                    </div>
                    <div class="send">SEND TO US</div>
                </div>
            </div>
            <div class="col-sm-7">
                <div class="block-address">
                    <div id="div_id" style="height:200px; width:100%"></div>
                    <div class="title">Công Ty TNHH Xây Dựng Minh Chương</div>
                    <div class="description">
                        <b>Contruction &#9679; Interior &#9679; Funiture</b><br>
                        <span class="company-address">160 Nơ Trang Long, P.14, Q. Bình Thạnh, TP.HCM * ĐT 38412839 - 3561818 &#9679; FAX: 35161818
                        <br>
                        FACTORY: LOREM ISSUM DOLOR SIT AMET</span>
                        <hr>
                        <span class="copy-right">@2016 MINH CHƯƠNG LTD. Web design by HaloZend</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="scroll-top" onclick="scrolltop()">
        <img src="<?php echo $linkImage?>scroll-top.png" alt="scroll-top">
    </div>
</section>
<script>
    jQuery(document).ready(function($) {
        $('#banner-slide').bjqs({
            animtype      : 'slide',
            height      : 505,
            width       : 1170,
            responsive  : true,
            randomstart   : true,
            automatic: true,
            paused: 0
        });
    });
</script>