<!--start block policy-->
<div class="container">
    <div class="row policy-block">
        <div class="about col-md-2 col-sm-4 col-xs-12">
            <ul >
                <li><span>Về chúng tôi</span></li>
                <li><a rel="nofollow" target="_blank" href="" title="Giới thiệu Sendo.vn">Giới thiệu web.vn</a></li>
                <li><a rel="nofollow" target="_blank" href="" title="Quy chế hoạt động">Quy chế hoạt động</a></li>
                <li><a rel="nofollow" target="_blank" href="" title="Các mức chế tài vi phạm/">Các mức chế tài vi phạm</a></li>
                <li>
                    <a rel="nofollow" target="_blank" href="" title="Liên hệ">Liên hệ</a>
                </li>
                <li><a rel="nofollow" target="_blank" href="" title="Sitemap">Sitemap</a></li>
                <li><a ref='nofollow' id="set_device" class="mobile" href="javascript:;" title="Sendo mobile">web Mobile</a></li>
            </ul>
        </div>
        <div class="buyer col-md-2 col-sm-4 col-xs-12">
            <ul>
                <li><span>Dành cho người mua</span></li>
                <li><a rel="nofollow" target="_blank" href="" title="Bảo vệ người mua">Bảo vệ người mua</a></li>
                <li><a rel="nofollow" target="_blank" href="" title="Quy định đối với người mua">Quy định đối với người mua </a></li>
                <li><a rel="nofollow" target="_blank" href="" title="Giải quyết khiếu nại"> Giải quyết khiếu nại </a></li>
                <li><a rel="nofollow" target="_blank" href="" title="Hướng dẫn người mua">Hướng dẫn người mua</a></li>

            </ul>
        </div>
        <div class="link col-md-2 col-sm-4 col-xs-12">
            <ul>
                <li>
                    <span>Liên kết</span>
                    <a target="_blank" href="" title="123Mua.vn: Mua bán Online chất lượng, giá tốt nhất thị trường" class="w123mua">www.123mua.vn</a>
                    <a target="_blank" href="" title="Nhịp sống Sendo - Tin Video, Tin Giải trí, Xu hướng thời trang cập nhật mỗi ngày" class="blogsendo">Nhịp sống web</a>
                </li>
                <li>
                    <a target="_blank" href="" title="Facebook Sendo" class="myfacebook icn">&nbsp;</a>
                    <a target="_blank" href="" title="Twitter Sendo" class="mytwitter icn">&nbsp;</a>
                    <a target="_blank" href="" title="Google+ Sendo" class="mygoogle icn">&nbsp;</a>
                    <a target="_blank" href="" title="Youtube Sendo" class="youtube icn">&nbsp;</a>
                    <a target="_blank" href="" title="Pinterest Sendo" class="pinterest icn">&nbsp;</a>
                </li>
                <li>
                    <a rel="nofollow"href="javascript:void(0)" title="Người mua chỉ thanh toán khi nhận hàng còn nguyên niêm phong, nguyên đai nguyên kiện. Áp dụng trên toàn quốc với các đơn hàng có giá trị dưới 10,000,000 đồng."  class="payment tool-tip">&nbsp;</a>
                    <a rel="nofollow" href="javascript:void(0)" title="Người mua có quyền khiếu nại và yêu cầu được hoàn tiền nếu hàng hóa không giống như mô tả hoặc không phải là món hàng mà bạn muốn mua." class="transaction tool-tip">&nbsp;</a>
                    <a target="_blank" href="" title="Mở shop trên Sendo.vn" class="openshop">&nbsp;</a>
                </li>
            </ul>
        </div>
        <div class="policy-block-right col-sm-12 col-md-6 col-xs-12 ">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1959.1501441183304!2d106.61289065791073!3d10.86474963219744!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x0!2zMTDCsDUxJzUzLjEiTiAxMDbCsDM2JzUwLjQiRQ!5e0!3m2!1svi!2s!4v1462958391441" width="100%" height="200" frameborder="0" style="border:0" allowfullscreen></iframe>
        </div>
        <div class="col-sm-12 col-xs-12">
            <div class="copyright">
                <span>Copyright © 2012 web.vn</span>
                <p>Số ĐKKD: 0312776486</p>
                <p>
                    Địa chỉ trụ sở: 153 Nguyễn Đình Chiểu, Phường 06, Quận 03, Tp.Hồ Chí Minh
                </p>
                <p>Địa chỉ liên hệ: Tòa nhà FPT Tân Thuận, Lô 29B-31B-33B, Đường Tân Thuận, KCX
                    Tân Thuận, Phường Tân Thuận Đông, Quận 7, Tp.HCM.
                </p>
                <p>
                    Điện thoại: 08 7300 1188
                </p>
            </div>
        </div>
    </div>
</div>
    
<!--end block policy-->