<!--Block HeaderNews-->
<div class="inner-wrap">
    <div id="header-text-nav-wrap" class="clearfix">
        <div id="header-left-section">
            <div id="header-logo-image">
                <a href="#" title="COLORMAG" rel="home">
                    <img src="http://demo.themegrill.com/colormag/wp-content/uploads/sites/20/2015/03/logo.png"
                        alt="COLORMAG">
                </a>
            </div>
            <!-- #header-logo-image -->
            <div id="header-text" class="screen-reader-text">
                <h3 id="site-title">
                    <a href="#" title="COLORMAG" rel="home">COLORMAG</a>
                </h3>
                <p id="site-description">Magazine WordPress theme for 2015</p>
                <!-- #site-description -->
            </div>
            <!-- #header-text -->
        </div>
        <!-- #header-left-section -->
        <div id="header-right-section">
            <div id="header-right-sidebar" class="clearfix">
                <aside id="colormag_728x90_advertisement_widget-9" class="widget widget_728x90_advertisement clearfix">
                    <div class="advertisement_728x90">
                        <div class="advertisement-content">
                            <a href="#" class="single_ad_728x90" target="_blank" rel="nofollow">
                                <img src="http://demo.themegrill.com/colormag/wp-content/uploads/sites/20/2015/07/ad-color-mag-large.jpg"
                                    width="728" height="90">
                            </a>
                        </div>
                    </div>
                </aside>
            </div>
        </div>
        <!-- #header-right-section -->
    </div>
    <!-- #header-text-nav-wrap -->
</div>