<!--Block Filter Price-->
<div class="filter">
    <div class="filter-title">
        <i class="fa fa-money"></i> KHOẢNG GIÁ
    </div><div class="filter-active-items"></div>
    <div class="filter-body">
        <div class="multiple-range">
            <div class="row">
                <div id="slider-container"></div>
                <div class="description-price">
                    <div class="from">0</div>
                    <div class="to">1.000.000</div>
                </div>
                <hr style="margin: 5px 0 15px;">
                <div class="col-md-12 text-center">
                    <input  style="display: inline-block; width: auto;" class="form-control input-sm priceMin" size="8" type="text" name="fromPrice" value="0" disabled="disabled">
                    &nbsp;&nbsp;-&nbsp;&nbsp;
                    <input style="display: inline-block; width: auto;" class="form-control input-sm priceMax" size="8" type="text" name="toPrice" value="1.000.000" disabled="disabled">
                </div>
            </div>
        </div>
    </div>
</div>
<!--End Filter Price-->