<div class="modal fade show-modal modal-update" id="<?php echo $id?>"tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title" id="myModalLabel">Thay đổi logo</h2>
            </div>
            <div class="modal-body">
                <form class="data-form" enctype="multipart/form-data"></form>
            </div>
        </div>
    </div>
</div>