<div class="boxcompare">
    <h3>Xem và so sánh Acer Iconia B1-723 với các sản phẩm tương tự</h3>
    <ul class="listcompare">
        <li>
        <a href="javascript:void(0)" title="Acer Iconia B1-723">
            <img class="lazy" src="https://cdn4.tgdd.vn/Products/Images/522/73498/acer-iconia-b1-723-300-200x200.jpg">
                <h3>Acer Iconia B1-723</h3>
                <strong>2.290.000₫</strong>
        </a>
            <figure class="bginfo">
                <span>Màn Hình: 7.0", 1024 x 600 pixel</span>
                <span>HDH: Android 5.1 - CPU: 4x1.3GHz</span>
                <span>RAM: 1GB - ROM: 16GB</span>
                <span>CAMERA: Trước 2.0MP  Sau 5.0MP</span>
                <span>Kết Nối: Wifi, 3G, Nghe gọi 2Sim</span><span>Pin: 3380mAh</span>
            </figure>
            <div class="viewed">Bạn đang xem</div>
        </li>
        <li class="sggProd">
            <form action="javascript:void(0)">
                <input class="addsearch" type="text" placeholder="Nhập tên máy tính bảng" onkeyup="SuggestCompare(this,event)">
                <i class="icondetail-mobile "></i>
            </form>
        </li>
    </ul>
</div>