<div class="block-nhip-song">
    <a target="_blank" href="#" class="title" title="Nhịp sống"><span>Nhịp sống</span></a>
    <div class="block-box">
        <a class="box" target="_blank" href="#" title="Khi 10 cô gái đáng yêu thử trang phục Halloween quyến rũ">
            <img src="<?php echo $this->view->basePath('public/files/posts/halloween.jpg')?>" title="Trang phục Halloween ấn tượng chỉ với một chiếc áo khoác" alt="Khi 10 cô gái đáng yêu thử trang phục Halloween quyến rũ" width="200" height="112">                        <span>Khi 10 cô gái đáng yêu thử trang phục Halloween quyến rũ</span>
        </a>
    </div>
    <ul class="box-links-nhip-song">
        <li><a target="_blank" href="" title="Nhận diện 8 vị trí trên cơ thể cần thoa kem chống nắng">Nhận diện 8 vị trí trên cơ thể cần thoa kem chống nắng</a></li>
    </ul>
</div>