<!--start block products home tab-->
<div id="product-home-tabs">
    <div class="tabs-carousel ui-tabs-panel ui-widget-content ui-corner-bottom" id="tabs-1" style="display: block;">
        <div class="cycleElementsContainer" id="cycle-1">
            <div id="elements-1">
                <div class="list_carousel">
                    <ul id="carousel1">
                        <?php
                            foreach($this->getDealProducts() as $val) {
                                ?>
                                <li class="ajax_block_product">
                                    <div class="product-item">
                                        <div class="product-container">
                                            <div class="product-image-container">
                                                <div class="item">
                                                    <a href="<?php echo $this->view->basePath('/'. $val['alias'] . '-' . $val['id'] . '.html') ?>"
                                                       title="<?php echo $val['name']?>" class="product_img_link outside">
                                                        <img
                                                            src="<?php echo $this->view->basePath('public/files/product/231x242/'. $val['image']) ?>"
                                                            alt="<?php echo $val['name']?>">
                                                        <span class="bg_hover"></span>
                                                    </a>
                                                </div>
                                            </div>
                                            <div class="box-button-container">
                                                <div class="button-container">
                                                    <div class="addtocart" data-id="<?php echo $val['id']?>">
                                                        <a class="ajax_add_to_cart_button cs_buttoncart" href="javascript:" rel="nofollow"
                                                           title="Add to cart">
                                                            <span>Add to cart</span>
                                                        </a>
                                                    </div>
                                                    <div class="wishlist" data-id="<?php echo $val['id']?>">
                                                        <a class="addToWishlist wishlistProd_11" href="javascript:" rel="11"
                                                           data-toggle="tooltip" data-placement="top"
                                                           data-original-title="Add to wishlist" rel="nofollow"> Add to Wishlist </a>
                                                    </div>
                                                    <div class="compare" data-id="<?php echo $val['id']?>">
                                                        <a class="add_to_compare" data-id-product="11"
                                                           title="Add to Compare" href="javascript:" rel="nofollow">Add to Compare</a>
                                                    </div>
                                                    
                                                        <a data-toggle="tooltip" data-placement="top"
                                                           data-original-title="Quick view"
                                                           href="javascript:" class="quick-view quickview" rel="nofollow">
                                                            <span>Quick view</span>
                                                        </a>
                                                    
                                                </div>
                                            </div>
                                            <div id="countdown_<?php echo $val['id']?>" class="timer clearfix">
                                                <ul class="clock">
                                                    <li><span class="days">1624</span><span>days</span></li>
                                                    <li><span class="hours">00</span><span>hours</span></li>
                                                    <li><span class="mins">02</span><span>mins</span></li>
                                                    <li><span class="secs">26</span><span>secs</span></li>
                                                </ul>
                                                <?php
                                                    echo '<script>
                                                    $(document).ready(function(){
                                                        countDown('. $val['id'] . ',' .date('Y',strtotime($val['deal_time'])). ',' . (int)(date('m',strtotime($val['deal_time'])) -1) . ','. date('y',strtotime($val['deal_time'])) .')
                                                    })
                                                    </script>';
                                                ?>
                                            </div>
                                        </div>
                                        <div class="csframe_product">
                                            <div class="product-title">
                                                <h5 class="name_product">
                                                    <a class="product-name"
                                                       href="<?php echo $this->view->basePath('/'. $val['alias'] . '-' . $val['id'] . '.html') ?>"
                                                       title="<?php echo $val['name']?>"><?php echo $val['name']?>
                                                    </a>
                                                </h5>
                                                <?php
                                                    if($val['sale_off']) {
                                                        echo '<span class=" old-price product-price">'. number_format($val['price'],0,',','.') .' đ</span>';
                                                    }
                                                ?>
                                            </div>
                                            <div class="content_price">
                                                <div class="comments_note">
                                                    <div class="star_content clearfix">
                                                        <div class="star star_on"></div>
                                                        <div class="star star_on"></div>
                                                        <div class="star star_on"></div>
                                                        <div class="star star_on"></div>
                                                        <div class="star"></div>
                                                    </div>
                                                </div>
                                                <?php
                                                    if($val['sale_off'])
                                                          echo '<span class="price product-price">'. number_format($val['sale_off'],0,',','.') .' đ</span>';
                                                    else
                                                        echo '<span class="price product-price">'. number_format($val['price'],0,',','.') .' đ</span>';
                                                ?>
                                            </div>
                                        </div>
                                </li>

                                <?php
                            }
                        ?>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
<!--end block products home tab-->
<script>
    function countDown(productId,year,month,day){
        ts = new Date(year,month,day);
        $('#countdown_' + productId).countdown({
            timestamp	: ts,
            callback	: function(days, hours, minutes, seconds){
                $('#countdown_'+productId + ' .days').html(days + ( days==1 ? '':'' ));
                $('#countdown_'+productId + ' .hours').html(hours + ( hours==1 ? '':'' ));
                $('#countdown_'+productId + ' .mins').html(minutes + ( minutes==1 ? '':'' ));
                $('#countdown_'+productId + ' .secs').html(seconds + ( seconds==1 ? '':'' ));
            }
        });
    }
</script>