<aside id="colormag_featured_posts_vertical_widget-5" class="widget widget_featured_posts widget_featured_posts_vertical widget_featured_meta clearfix">      <h3 class="widget-title" style="border-bottom-color:#a38a6d;"><span style="background-color:#a38a6d;">News</span></h3>                                 <div class="first-post">               <div class="single-article clearfix">
            <figure><a href="http://demo.themegrill.com/colormag/2015/03/24/destruction-in-montania/" title="Destruction in Montania"><img width="390" height="205" src="http://demo.themegrill.com/colormag/wp-content/uploads/sites/20/2015/03/fireman-100722_1280-390x205.jpg" class="attachment-colormag-featured-post-medium size-colormag-featured-post-medium wp-post-image" alt="Destruction in Montania" title="Destruction in Montania"></a></figure>                  <div class="article-content">
                <div class="above-entry-meta"><span class="cat-links"><a href="http://demo.themegrill.com/colormag/category/general/" style="background:#a38a6d" rel="category tag">General</a>&nbsp;<a href="http://demo.themegrill.com/colormag/category/latest/" style="background:#e5e220" rel="category tag">Latest</a>&nbsp;<a href="http://demo.themegrill.com/colormag/category/news/" style="background:#bfd6af" rel="category tag">News</a>&nbsp;</span></div>                     <h3 class="entry-title">
                    <a href="http://demo.themegrill.com/colormag/2015/03/24/destruction-in-montania/" title="Destruction in Montania">Destruction in Montania</a>
                </h3>
                <div class="below-entry-meta">
                    <span class="posted-on"><a href="http://demo.themegrill.com/colormag/2015/03/24/destruction-in-montania/" title="7:57 am" rel="bookmark"><i class="fa fa-calendar-o"></i> <time class="entry-date published" datetime="2015-03-24T07:57:31+00:00">March 24, 2015</time></a></span>                        <span class="byline"><span class="author vcard"><i class="fa fa-user"></i><a class="url fn n" href="http://demo.themegrill.com/colormag/author/demothemegrill/" title="TG-Demo Team">TG-Demo Team</a></span></span>
                    <span class="comments"><i class="fa fa-comment"></i><span>Comments Off<span class="screen-reader-text"> on Destruction in Montania</span></span></span>
                </div>
                <div class="entry-content">
                    <p>Nunc consectetur ipsum nisi, ut pellentesque felis tempus vitae. Integer eget lacinia nunc. Vestibulum consectetur convallis augue id egestas. Nullam</p>
                </div>
            </div>

        </div>
    </div>                                 <div class="following-post">               <div class="single-article clearfix">
            <figure><a href="http://demo.themegrill.com/colormag/2015/03/24/invention-of-advance-technology/" title="Invention of Advance Technology"><img width="130" height="90" src="http://demo.themegrill.com/colormag/wp-content/uploads/sites/20/2015/03/vehicle-193213_1280-130x90.jpg" class="attachment-colormag-featured-post-small size-colormag-featured-post-small wp-post-image" alt="Invention of Advance Technology" title="Invention of Advance Technology" srcset="http://demo.themegrill.com/colormag/wp-content/uploads/sites/20/2015/03/vehicle-193213_1280-392x272.jpg 392w, http://demo.themegrill.com/colormag/wp-content/uploads/sites/20/2015/03/vehicle-193213_1280-130x90.jpg 130w" sizes="(max-width: 130px) 100vw, 130px"></a></figure>                  <div class="article-content">
                <div class="above-entry-meta"><span class="cat-links"><a href="http://demo.themegrill.com/colormag/category/general/" style="background:#a38a6d" rel="category tag">General</a>&nbsp;<a href="http://demo.themegrill.com/colormag/category/latest/" style="background:#e5e220" rel="category tag">Latest</a>&nbsp;<a href="http://demo.themegrill.com/colormag/category/technology/" style="background:#777fce" rel="category tag">Technology</a>&nbsp;</span></div>                     <h3 class="entry-title">
                    <a href="http://demo.themegrill.com/colormag/2015/03/24/invention-of-advance-technology/" title="Invention of Advance Technology">Invention of Advance Technology</a>
                </h3>
                <div class="below-entry-meta">
                    <span class="posted-on"><a href="http://demo.themegrill.com/colormag/2015/03/24/invention-of-advance-technology/" title="7:47 am" rel="bookmark"><i class="fa fa-calendar-o"></i> <time class="entry-date published" datetime="2015-03-24T07:47:05+00:00">March 24, 2015</time></a></span>                        <span class="byline"><span class="author vcard"><i class="fa fa-user"></i><a class="url fn n" href="http://demo.themegrill.com/colormag/author/demothemegrill/" title="TG-Demo Team">TG-Demo Team</a></span></span>
                    <span class="comments"><i class="fa fa-comment"></i><span>Comments Off<span class="screen-reader-text"> on Invention of Advance Technology</span></span></span>
                </div>
            </div>

        </div>
        <div class="single-article clearfix">
            <figure><a href="http://demo.themegrill.com/colormag/2015/03/24/swimming-record/" title="Swimming Record"><img width="130" height="90" src="http://demo.themegrill.com/colormag/wp-content/uploads/sites/20/2015/03/swimmer-583667_1280-130x90.jpg" class="attachment-colormag-featured-post-small size-colormag-featured-post-small wp-post-image" alt="Swimming Record" title="Swimming Record" srcset="http://demo.themegrill.com/colormag/wp-content/uploads/sites/20/2015/03/swimmer-583667_1280-392x272.jpg 392w, http://demo.themegrill.com/colormag/wp-content/uploads/sites/20/2015/03/swimmer-583667_1280-130x90.jpg 130w" sizes="(max-width: 130px) 100vw, 130px"></a></figure>                  <div class="article-content">
                <div class="above-entry-meta"><span class="cat-links"><a href="http://demo.themegrill.com/colormag/category/general/" style="background:#a38a6d" rel="category tag">General</a>&nbsp;<a href="http://demo.themegrill.com/colormag/category/latest/" style="background:#e5e220" rel="category tag">Latest</a>&nbsp;<a href="http://demo.themegrill.com/colormag/category/sports/" style="background:#dd5a5a" rel="category tag">Sports</a>&nbsp;</span></div>                     <h3 class="entry-title">
                    <a href="http://demo.themegrill.com/colormag/2015/03/24/swimming-record/" title="Swimming Record">Swimming Record</a>
                </h3>
                <div class="below-entry-meta">
                    <span class="posted-on"><a href="http://demo.themegrill.com/colormag/2015/03/24/swimming-record/" title="7:44 am" rel="bookmark"><i class="fa fa-calendar-o"></i> <time class="entry-date published" datetime="2015-03-24T07:44:03+00:00">March 24, 2015</time></a></span>                        <span class="byline"><span class="author vcard"><i class="fa fa-user"></i><a class="url fn n" href="http://demo.themegrill.com/colormag/author/demothemegrill/" title="TG-Demo Team">TG-Demo Team</a></span></span>
                    <span class="comments"><i class="fa fa-comment"></i><span>Comments Off<span class="screen-reader-text"> on Swimming Record</span></span></span>
                </div>
            </div>

        </div>
        <div class="single-article clearfix">
            <figure><a href="http://demo.themegrill.com/colormag/2015/03/24/news-with-coffee/" title="News with Coffee"><img width="130" height="90" src="http://demo.themegrill.com/colormag/wp-content/uploads/sites/20/2015/03/newspapers-444453_1280-130x90.jpg" class="attachment-colormag-featured-post-small size-colormag-featured-post-small wp-post-image" alt="News with Coffee" title="News with Coffee" srcset="http://demo.themegrill.com/colormag/wp-content/uploads/sites/20/2015/03/newspapers-444453_1280-392x272.jpg 392w, http://demo.themegrill.com/colormag/wp-content/uploads/sites/20/2015/03/newspapers-444453_1280-130x90.jpg 130w" sizes="(max-width: 130px) 100vw, 130px"></a></figure>                  <div class="article-content">
                <div class="above-entry-meta"><span class="cat-links"><a href="http://demo.themegrill.com/colormag/category/general/" style="background:#a38a6d" rel="category tag">General</a>&nbsp;<a href="http://demo.themegrill.com/colormag/category/latest/" style="background:#e5e220" rel="category tag">Latest</a>&nbsp;</span></div>                     <h3 class="entry-title">
                    <a href="http://demo.themegrill.com/colormag/2015/03/24/news-with-coffee/" title="News with Coffee">News with Coffee</a>
                </h3>
                <div class="below-entry-meta">
                    <span class="posted-on"><a href="http://demo.themegrill.com/colormag/2015/03/24/news-with-coffee/" title="7:42 am" rel="bookmark"><i class="fa fa-calendar-o"></i> <time class="entry-date published" datetime="2015-03-24T07:42:19+00:00">March 24, 2015</time></a></span>                        <span class="byline"><span class="author vcard"><i class="fa fa-user"></i><a class="url fn n" href="http://demo.themegrill.com/colormag/author/demothemegrill/" title="TG-Demo Team">TG-Demo Team</a></span></span>
                    <span class="comments"><i class="fa fa-comment"></i><span>Comments Off<span class="screen-reader-text"> on News with Coffee</span></span></span>
                </div>
            </div>

        </div>
    </div>      </aside>