<header class="page-header">
    <h1 class="page-title" style="border-bottom-color: #bd4cce">
    <span style="background-color: #bd4cce"><?php echo $this->category->name?></span>
    </h1>
</header>
<div class="article-container">
    <article class="post type-post status-publish format-standard has-post-thumbnail hentry category-fashion category-female category-style">
        <div class="featured-image">
            <a href="#" title="">
                <img width="800" height="445" src="<?php echo $this->basePath('public/files/posts-category/') . $this->category->image?>"
                alt="<?php echo $this->category->name ?>">
            </a>
        </div>
        <div class="article-content clearfix">
            <header class="entry-header">
                <h2 class="entry-title">
                <a href="#" title="Looks from the Roswana, 2015"><?php echo $this->category->name ?></a>
                </h2>
            </header>
            <div class="below-entry-meta">
                <span class="posted-on">
                    <a href="#" title="6:31 am" rel="bookmark">
                    <i class="fa fa-calendar-o"></i>
                        <?php echo $this->category->created_date ?>
                    </a>
                </span>
                <span class="byline">
                    <span class="author vcard">
                        <i class="fa fa-user"></i>
                        <a class="url fn n" href="#" rel="nofollow" title="<?php echo $this->category->create_by ?>"><?php echo $this->category->created_by ?></a>
                    </span>
                </span>
            </div>
            <div class="entry-content clearfix">
                <p><?php echo $this->category->description ?></p>
            </div>
        </article>
        <?php
            foreach($this->products as $val) {
                echo '<article id="post-66"
                         class="post-66 post type-post status-publish format-standard has-post-thumbnail hentry category-fashion category-general">
                    <div class="featured-image">
                        <a href="#" title="'. $val['postsName'] .'">
                            <img src="'. $this->basePath('public/files/posts/390x220/'. $val['postsImage']) .'" alt="'. $val['postsName'] .'">
                        </a>
                    </div>
                    <div class="article-content clearfix">
                        <header class="entry-header">
                            <h2 class="entry-title">
                                <a href="#" title="Color your Hair">'. $val['postsName'] .'</a>
                            </h2>
                        </header>
                        <div class="below-entry-meta">
                            <span class="posted-on">
                                <a href="#" title="6:27 am" rel="bookmark">
                                    <i class="fa fa-calendar-o"></i>
                                    '. $val['postsCreatedDate'] .'
                                </a>
                            </span>
                        </div>
                    </div>
                </article>';
            }
        ?>
</div>