<div class="row-fluid">
    <div class="span12">
        <div class="switch-board gray">
            <ul class="clearfix switch-item">
                <li>
                    <a href="<?php echo $this->basePath('admin/group/index') ?>" class=" bondi-blue">
                        <i class="fa fa-group"></i>
                        <span>Nhóm</span>
                    </a>
                </li>
                <li>
                    <span class="notify-tip">30</span>
                    <a href="<?php echo $this->basePath('admin/user/index') ?>" class="brown">
                        <i class="fa fa-user" aria-hidden="true"></i>
                        <span>Thành Viên</span>
                    </a>
                </li>
                <li>
                    <a href="<?php echo $this->basePath('admin/posts-category/index') ?>" class="orange">
                        <i class="fa fa-suitcase"></i>
                        <span>Chuyên Mục</span>
                    </a>
                </li>
                <li>
                    <a href="<?php echo $this->basePath('admin/posts/index') ?>" class=" blue-violate">
                        <i class="fa fa-file-text-o" aria-hidden="true"></i>
                        <span>Bài Viết</span></a>
                </li>
                <li>
                    <a href="<?php echo $this->basePath('admin/tags/index') ?>" class=" magenta">
                        <i class="fa fa-tags"></i>
                        <span>Thẻ SEO</span></a>
                </li>
                <li>
                    <a href="<?php echo $this->basePath('admin/pages/index') ?>" class="green">
                        <i class="fa fa-file-o"></i>
                        <span>Trang</span></a>
                </li>
            </ul>
        </div>
    </div>
</div>
<section id="auth-button"></section>
<section id="view-selector"></section>
<section id="timeline"></section>