<div class="container-fluid cls" id="menu">
    <div class="row nav-bar-menu">
        <div class="col-md-2 nav-category">
            <span class="category">Danh Mục</span>
        </div>
        <div class="col-md-10">
            <div class="list-menu">
                <ul>
                    <li><a href="<?php echo $this->view->url('productProperties',array('action' => 'deal-moi','extension' => 'html'))?>">DEAL Mới</a></li>
                    <li><a href="<?php echo $this->view->url('productProperties',array('action' => 'deal-ban-chay','extension' => 'html'))?>">DEAL Bán Chạy</a></li>
                    <li><a href="<?php echo $this->view->url('productProperties',array('action' => 'deal-hot','extension' => 'html'))?>">DEAL Hot</a></li>
                    <li><a href="#">Thông Tin</a></li>
                    <li><a href="#">Liên Hệ</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>