<div class="container-fluid cls" id="menu">
    <div class="row nav-bar-menu">
        <div class="col-md-2 nav-category">
            <span class="category">Danh Mục</span>
        </div>
        <div class="col-md-10">
            <div class="list-menu">
                <ul>
                    <li><a href="#">DEAL Mới</a></li>
                    <li><a href="#">DEAL Bán Chạy</a></li>
                    <li><a href="#">DEAL Hot</a></li>
                    <li><a href="#">Thông Tin</a></li>
                    <li><a href="#">Liên Hệ</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>