<?php
$arr = array(
    array('title' => 'Mã đơn hàng'),
    array('title' => 'Người mua'),
    array('title' => 'Điện Thoại'),
    array('title' => 'TT'),
    array('title' => 'Tổng tiền'),
    array('title' => 'Ngày đặt hàng'),
    array('title' => 'Trạng Thái'),
    array('title' => 'Chức năng'),
    array('title' => 'Id')
);
$this->datatable('cart', $arr);
$button = '<div class="modal-footer">
                 <button type="button" class="btn btn-default" id="order-canceled">Hủy đơn hàng</button>
                 <button type="button" class="btn btn-warning" id="order-shipping">Giao Hàng</button>
                 <button type="button" class="btn btn-success" id="order-complete">Hoàn tất</button>
           </div>';
$this->modal('order', $this->render('view.phtml') ,'modal-md','',$button);
?>
