<div class="container-fluid container-main" style="top: 74px;">
    <section id="content">
        <div class="row">
            <div class="col-md-6" style="border-right: 1px solid #eee;">
                <h4 class="title">Thông Tin Chủ Đơn Hàng</h4>
                <p><strong>Tên khách hàng: </strong><span id="username"></span></p>
                <p><strong>Số điện thoại: </strong><span id="phone"></span></p>
                <p><strong>Email: </strong><span id="email"></span></p>
                <p><strong>Địa chỉ giao hàng: </strong><span id="shipping_address"></span></p>
                <p><strong>Ngày đặt hàng: </strong><span id="time_order"></span></p>
            </div>
            <div class="col-md-6">
                <h4 class="title">Thông Tin Hóa Đơn</h4>
                <ul class="order-info"></ul>
            </div>
            <div class="col-md-12" style="text-align: right; margin-top: 20px;">
                <span>Tổng giá trị hóa đơn: </span><strong id="totalMoney"></strong>
            </div>
        </div>
    </section>
</div>