<div class="boxaccess">
<h3><span class="sumAcc">9</span> phụ kiện phù hợp với Acer Iconia B1-723</h3>
    <div class="optview">
        <div id="access">
            <div class="owl-wrapper-outer">
                <div class="item">
                    <a href="/tai-nghe-day/tai-nghe-chup-tai-kanen-ip-2050">
                        <img class="lazyOwl" width="260" height="280" alt="Tai nghe chụp tai Kanen IP-2050" src="https://cdn3.tgdd.vn/Products/Images/54/68924/tai-nghe-chup-tai-kanen-ip-2050-new-460x520.jpg" style="display: block;">
                        <h3>Tai nghe chụp tai Kanen IP-2050</h3>
                        <div class="color">
                            <span class="colortext">1 màu: </span>
                            <ul class="lstcolor">
                                <li style="background-color: #FF0000"></li>
                            </ul>
                        </div>
                        <strong>320.000₫</strong>
                    </a>
                    <div class="together">
                        <i data-id="68924" data-value="320000" class="icondetail-uncheck"></i>
                        <div data-value="320000">Mua phụ kiện này</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>