<form method="post" id="<?php echo $this->idForm ?>" class="form-horizontal" action="<?php echo $this->action ?>">
    <div class="panel " id="meta_fieldset_general">
        <div class="panel-heading">
            <i class="fa fa-<?php echo $this->icon ?>"></i>
            <?php echo $this->title ?>
        </div>
        <div class="form-wrapper">
            <div class="form-group">
                    <?php
                        foreach($this->data as $val){
                            echo '<div class="row">
                                        <label class="control-label col-lg-3">
                                            '. $val['label'] .'
                                        </label>
                                        <div class="col-lg-9">
                                            <input class="form-control " type="'. $val['type'] .'" size="5" name="'. $val['name'] .'" value="'. $val['value'] .'">
                                        </div>
                                  </div>';
                        }
                    ?>
            </div>
        </div>
        <div class="panel-footer">
            <button type="submit" class="btn btn-default pull-right">
                <i class="fa fa-floppy-o"></i> Save
            </button>
        </div>
    </div>
</form>