<?php $data = $this->_data; ?>
<!--start block nav left home page module-->
<div class='nav-left-homepage'>
    <div class="nav-main-box" id="nav-main-home">
        <ul class="nav-main for-home">
            <?php
            $i = 0;
            foreach($data as $value){
                if($value['level'] == 1){ ?>

                    <li class="menuItem" id="category-<?php echo $i ?>" data-id="<?php echo $value['id']?>">
                        <strong>
                            <a href="<?php echo $this->view->basePath('/' . $value['alias'] . '-' . $value['id'])?>" title="Thời trang nữ"><?php echo $value['name']?></a>
                            <span><i class="fa fa-angle-right"></i></span>
                        </strong>
                        <!-- <div class="guide">
                            <a href="<?php echo $_SERVER['REQUEST_URI'] .'/' . $value['alias'] . '-' . $value['id'] ?>" title="Áo nữ">Áo nữ</a>
                        </div> -->
                        <div class="sub-cate">
                            <?php
                                if(isset($imgBanner[$value['id']]) && isset($imgBanner[$value['id']]))
                                    $backImg = 'style="background: url('. $this->view->basePath('public/files/upload/') . $imgBanner[$value['id']] .')"';
                                else
                                    $backImg = 'style="background: white"';
                            ?>
                            <div class="sub-cate-inner hover-edit" <?php echo $backImg?>>
                                <div class="list-item">
                                    <span><b>Chuyên Mục</b></span>
                                    <ul>
                                    <?php foreach ($data as $val){
                                        if($val['level'] == 2 && $val['parent'] == $value['id']){ ?>
                                                <li>
                                                    <a class="title" href="<?php echo $this->view->basePath('/' . $val['alias'] . '-' . $val['id']) ?>" title="<?php echo $val['name']?>"><?php echo $val['name']?></a>
                                                </li>
                                        <?php }} ?>
                                    </ul>
                                </div>
                                <div class="list-item">
                                    <span><b>Thương Hiệu</b></span>
                                    <ul>
                                        <?php 
                                        $manufacturer = $this->_table->getManufacturerByCategory($value['id'],['task' => 'index']);
                                        foreach ($manufacturer as $val) {
                                            echo '<li><a href="#">', $val['manufacturerName'] ,'</a></li>';
                                        }
                                        ?>
                                    </ul>
                                </div>
                                <?php if($this->view->identity() && $this->view->identity()->group_id == 1){ ?>
                                    <div class="btn-edit" data-id="<?php echo $value['id']?>" data-img="<?php echo isset($imgBanner[$value['id']]) ? $imgBanner[$value['id']] : ''?>">
                                        <img src="<?php echo $this->view->basePath('public/template/frontend/images/btn-edit.png') ?>" alt="">
                                    </div>
                                <?php } ?>
                            </div>
                        </div>
                    </li>
                <?php ++$i; }} ?>
        </ul>
    </div>
</div>
<!--end block nav left home page module-->