<!--start block support-->
<div class="small-b no-float">
    <div class="policy_sendo ">
        <div class='policy_sendo_box buystep'><a class="buystep" href="https://www.sendo.vn/huong-dan/huong-dan-mua-hang/" title="Các bước mua hàng" rel="nofollow" target="_blank">Các bước mua hàng</a></div>
        <div class='policy_sendo_box shippingstep'><a href="https://www.sendo.vn/huong-dan/giao-hang-toan-quoc/" class="shippingstep" title="Phương thức vận chuyển" rel="nofollow" target="_blank">Phương thức vận chuyển</a></div>
        <div class='policy_sendo_box paymentstep'><a href="https://www.sendo.vn/huong-dan/cach-thuc-thanh-toan/" class="paymentstep" title="Cách thức thanh toán" rel="nofollow" target="_blank">Cách thức thanh toán</a></div>
    </div>
    <div class="help_all nologin">
        <div class="cs">
            <div class="title">hỗ trợ khách hàng</div>
            <div class="phoneno">
                <p>Toàn quốc: <b>1900 6000</b></p>
                <span>(1.000 đồng/phút)</span>
            </div>
        </div>
        <div class="email">
            Email: <a href="mailto:hotro@sendo.vn" title="Email hỗ trợ của sendo.vn">hotro@webseo.vn</a>
        </div>
    </div>
</div>
<!--end block support-->