<div class="container-fluid container-main" style="top: 74px;">
    <section id="content">
        <!-- Begin Content -->

        <div class="row-fluid">
            <div class="span12">
                <?php echo $this->form()->openTag($this->form) ?>
                <div class="form-inline form-inline-header">
                    <div class="control-group">
                        <?php echo $this->formRow($this->form->get('name')->get('name')->setLabel('Tên Sản Phẩm')); ?>
                    </div>
                    <div class="control-group">
                        <?php echo $this->formRow($this->form->get('alias')->get('alias')); ?>
                    </div>
                </div>

                <div class="form-horizontal">

                    <ul class="nav nav-tabs" id="myTabTabs">
                        <li class="active"><a href="#general" data-toggle="tab">Mô Tả</a></li>
                        <li class="" id="product-price"><a href="#show-price" data-toggle="tab">Thông Tin Sản Phẩm</a></li>
                        <li class=""><a href="#publishing" data-toggle="tab">Lịch Sử Và SEO</a></li>
                        <li class="" id="up-img"><a href="#attrib-basic" data-toggle="tab">Ảnh Slider</a></li>
                        <li class="" id="img-zoom"><a href="#add-zoom-image" data-toggle="tab">Ảnh Zoom</a></li>
                    </ul>
                    <div class="tab-content" id="myTabContent">

                        <div id="general" class="tab-pane active">
                            <div class="row-fluid">
                                <div class="span9">
                                    <div class="fckeditor">
                                        <?php $this->fck('', 'description') ?>
                                    </div>
                                </div>
                                <div class="span3">
                                    <fieldset class="form-vertical">
                                        <div class="control-group">
                                            <label for="status" class="control-label"><span>Chuyên Mục</span>
                                                <?php
                                                $html = '<select name="parent" class="form-control col-sm-2" style="margin-top: 6px;" id="parent">
                                                            <option value="0">--- Vui lòng chọn ---</option>';
                                                foreach ($this->itemSelectBox as $val) {
                                                    $str = str_repeat('- ', $val['level'] - 1);
                                                    if ($val['level'] > 1) {
                                                        $html .= '<option value="' . $val['id'] . '">' . $str . $val['name'] . '</option>';
                                                    } else {
                                                        $html .= '<option value="' . $val['id'] . '">' . $val['name'] . '</option>';
                                                    }
                                                }
                                                $html .= '</option>';
                                                echo $html;
                                                ?>
                                                </select>
                                            </label>
                                        </div>
                                        <div class="control-group">
                                            <?php echo $this->formRow($this->form->get('code')); ?>
                                        </div>
                                        <div class="control-group">
                                            <label for="status" class="control-label">Ảnh đại diện</label>
                                            <div class="control-group" id="product-image"></div>
                                            <?php echo $this->formRow($this->form->get('upload')->get('picture')->setName('image')); ?>
                                            <input type="submit" value="upload" id="upload"/>
                                        </div>
                                    </fieldset>
                                </div>
                            </div>

                        </div>

                        <div id="publishing" class="tab-pane">
                            <div class="row-fluid form-horizontal-desktop">
                                <div class="span6">
                                    <div class="control-group">
                                        <?php echo $this->formRow($this->form->get('info')->get('created_date')); ?>
                                    </div>

                                    <div class="control-group">
                                        <?php echo $this->formRow($this->form->get('info')->get('created_by')); ?>
                                    </div>

                                    <div class="control-group">
                                        <?php echo $this->formRow($this->form->get('info')->get('modified_date')); ?>
                                    </div>

                                    <div class="control-group">
                                        <?php echo $this->formRow($this->form->get('info')->get('modified_by')); ?>
                                    </div>

                                    <div class="control-group">
                                        <?php echo $this->formRow($this->form->get('info')->get('hits')); ?>
                                    </div>
                                </div>
                                <div class="span6">


                                    <div class="control-group">
                                        <?php echo $this->formRow($this->form->get('SEO')->get('meta_description')); ?>
                                    </div>

                                    <div class="control-group">
                                        <?php echo $this->formRow($this->form->get('SEO')->get('meta_keyword')); ?>
                                    </div>
                                </div>
                            </div>

                        </div>

                        <div id="attrib-basic" class="tab-pane">
                            <div class="control-group" id="show-img"></div>
                            <div class="control-group" id="upload-img">
                                <input id="file" type="file" name="file" multiple class="file" data-overwrite-initial="false">
                            </div>
                        </div>
                        <div id="add-zoom-image" class="tab-pane">
                            <div class="control-group" id="show-zoom-img"></div>
                            <div class="control-group" id="upload-zoom-img">
                                <input id="zoom-image" type="file" name="file" multiple class="file" data-overwrite-initial="false">
                            </div>
                        </div>
                        <div id="show-price" class="tab-pane">
                            <div class="row-fluid form-horizontal-desktop">
                                <div class="span6 col-md-4">
                                    <div class="control-group">
                                        <?php echo $this->formRow($this->form->get('price')); ?>
                                    </div>

                                    <div class="control-group">
                                        <?php echo $this->formRow($this->form->get('sale_off')); ?>
                                    </div>

                                    <div class="control-group">
                                        <?php echo $this->formRow($this->form->get('percent_discount')); ?>
                                    </div>

                                    <div class="control-group">
                                        <label for="trademark" class="col-xs-4 control-label">Thương Hiệu</label>
                                        <?php
                                        $html = '<select name="trademark" class="form-control" id="trademark"><option value="0">--- Vui lòng chọn ---</option>';
                                        foreach($this->slbManufacturer as $val){
                                            $html .= '<option value="' . $val['id'] . '">' . $val['name'] . '</option>';
                                        }
                                        echo $html,'</option></select>';
                                        ?>
                                    </div>
                                </div>
                                <div class="span6 col-md-4 choose-size">
                                    <div class="control-group">
                                        <?php echo $this->formRow($this->form->get('size')); ?>
                                        <i class="fa fa-search"></i>
                                        <i class="fa fa-plus" onclick="addSize()"></i>
                                        <div class="size-drop">
                                            <ul class="size-results"></ul>
                                        </div>
                                    </div>
                                    <div class="list-size" style="display: none">
                                        <ul></ul>
                                    </div>
                                </div>
                                <div class="col-md-4 deal_time span6">
                                    <div class="control-group">
                                        <label for="price" class="col-xs-4 control-label" style="margin-left: -20px">Deal time:</label>
                                        <input type="date" class="from-control input-large-text" name="deal_time" id="deal_time">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <input type="hidden" name="id" id="id" />
                    <input type="hidden" name="action" id="action"/>
                    <input type="hidden" id="controller" value="product"/>
                    <?php echo $this->form()->closeTag($this->form) ?>

                </div>
            </div>
            <!-- End Content -->
    </section>

</div>