<?php
$arr = array(
    array('title' => 'Tên Sản Phẩm'),
    array('title' => 'Ảnh'),
    array('title' => 'Code'),
    array('title' => 'Thương hiệu'),
    array('title' => 'Tình trạng'),
    array('title' => 'Deal'),
    array('title' => 'Hot'),
    array('title' => 'Chuyên mục'),
    array('title' => 'Giá gốc (VNĐ)'),
    array('title' => 'Giá bán (VNĐ)'),
    array('title' => 'Xem'),
    array('title' => 'Chức năng'),
    array('title' => 'Id')
);
$this->datatable('product', $arr);
$this->modal('product', $this->render('edit.phtml'), 'modal-lg');
?>
