<!--Block Filter Price-->
<div class="filter">
    <div class="filter-title">
        <i class="fa fa-star"></i> ĐÁNH GIÁ
    </div>
    <div class="filter-body">
        <div class="rating__labels">
            <div class="rating__stars-link rating__stars" data-num="5">
                <input type="radio" name="rate" value="5">
                <div class="rating__stars-link-cont">
                    <div class="rating__stars-count-5">
                        <span class="icon-svg icon_product-seller-rating-star_state_normal"></span>
                        <span class="icon-svg icon_product-seller-rating-star_state_normal"></span>
                        <span class="icon-svg icon_product-seller-rating-star_state_normal"></span>
                        <span class="icon-svg icon_product-seller-rating-star_state_normal"></span>
                        <span class="icon-svg icon_product-seller-rating-star_state_normal"></span>
                    </div>
                    <div class="rating__stars-count-5">
                        <span class="icon-svg rating__star-orange"></span>
                        <span class="icon-svg rating__star-orange"></span>
                        <span class="icon-svg rating__star-orange"></span>
                        <span class="icon-svg rating__star-orange"></span>
                        <span class="icon-svg rating__star-orange"></span>
                    </div>
                </div>
            </div>
            <div class="rating__stars-link rating__stars" data-num="4">
                <input type="radio" name="rate" value="4">
                <div class="rating__stars-link-cont" >
                    <div class="rating__stars-count-4" >
                        <span class="icon-svg icon_product-seller-rating-star_state_normal"></span>
                        <span class="icon-svg icon_product-seller-rating-star_state_normal"></span>
                        <span class="icon-svg icon_product-seller-rating-star_state_normal"></span>
                        <span class="icon-svg icon_product-seller-rating-star_state_normal"></span>
                        <span class="icon-svg icon_product-seller-rating-star_state_normal"></span>
                    </div>
                    <div class="rating__stars-count-4" >
                        <span class="icon-svg rating__star-orange"></span>
                        <span class="icon-svg rating__star-orange"></span>
                        <span class="icon-svg rating__star-orange"></span>
                        <span class="icon-svg rating__star-orange"></span>
                        <span class="icon-svg rating__star-orange"></span>
                    </div>
                </div>
            </div>
            <div class="rating__stars-link rating__stars" data-num="3">
                <input type="radio" name="rate" value="3">
                <div class="rating__stars-link-cont" >
                    <div class="rating__stars-count-3" >
                        <span class="icon-svg icon_product-seller-rating-star_state_normal"></span>
                        <span class="icon-svg icon_product-seller-rating-star_state_normal"></span>
                        <span class="icon-svg icon_product-seller-rating-star_state_normal"></span>
                        <span class="icon-svg icon_product-seller-rating-star_state_normal"></span>
                        <span class="icon-svg icon_product-seller-rating-star_state_normal"></span>
                    </div>
                    <div class="rating__stars-count-3" >
                        <span class="icon-svg rating__star-orange"></span>
                        <span class="icon-svg rating__star-orange"></span>
                        <span class="icon-svg rating__star-orange"></span>
                        <span class="icon-svg rating__star-orange"></span>
                        <span class="icon-svg rating__star-orange"></span>
                    </div>
                </div>
            </div>
            <div class="rating__stars-link rating__stars" data-num="2">
                <input type="radio" name="rate" value="2">
                <div class="rating__stars-link-cont" >
                    <div class="rating__stars-count-2" >
                        <span class="icon-svg icon_product-seller-rating-star_state_normal"></span>
                        <span class="icon-svg icon_product-seller-rating-star_state_normal"></span>
                        <span class="icon-svg icon_product-seller-rating-star_state_normal"></span>
                        <span class="icon-svg icon_product-seller-rating-star_state_normal"></span>
                        <span class="icon-svg icon_product-seller-rating-star_state_normal"></span>
                    </div>
                    <div class="rating__stars-count-2" >
                        <span class="icon-svg rating__star-orange"></span>
                        <span class="icon-svg rating__star-orange"></span>
                        <span class="icon-svg rating__star-orange"></span>
                        <span class="icon-svg rating__star-orange"></span>
                        <span class="icon-svg rating__star-orange"></span>
                    </div>
                </div>
            </div>
            <div class="rating__stars-link rating__stars" data-num="1">
                <input type="radio" name="rate" value="1">
                <div class="rating__stars-link-cont">
                    <div class="rating__stars-count-1">
                        <span class="icon-svg icon_product-seller-rating-star_state_normal"></span>
                        <span class="icon-svg icon_product-seller-rating-star_state_normal"></span>
                        <span class="icon-svg icon_product-seller-rating-star_state_normal"></span>
                        <span class="icon-svg icon_product-seller-rating-star_state_normal"></span>
                        <span class="icon-svg icon_product-seller-rating-star_state_normal"></span>
                    </div>
                    <div class="rating__stars-count-1">
                        <span class="icon-svg rating__star-orange"></span>
                        <span class="icon-svg rating__star-orange"></span>
                        <span class="icon-svg rating__star-orange"></span>
                        <span class="icon-svg rating__star-orange"></span>
                        <span class="icon-svg rating__star-orange"></span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--End Filter Price-->