<!--Block Menu News-->
<div id="site-navigation-sticky-wrapper" class="sticky-wrapper" style="height: 46px;">
    <nav id="site-navigation" class="main-navigation clearfix" role="navigation" style="width: 1200px;">
        <div class="inner-wrap clearfix">
            <div class="home-icon">
                <a href="" title="COLORMAG"><i class="fa fa-home"></i></a>
            </div>
            <h4 class="menu-toggle"></h4>

            <div class="menu-primary-container">
                <ul id="menu-primary" class="menunav-menu">
                    <li id="menu-item-221"
                        class="menu-item menu-item-type-custom menu-item-object-custom menu-item-221"><a
                            href="#">Download</a></li>
                    <li id="menu-item-175"
                        class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-175"><a
                            href="#">Sports</a></li>
                    <li id="menu-item-32"
                        class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-32"><a
                            href="#">Politics</a></li>
                    <li id="menu-item-176"
                        class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-176"><a
                            href="#">Technology</a></li>
                    <li id="menu-item-177"
                        class="menu-item menu-item-type-taxonomy menu-item-object-category current-menu-item menu-item-177">
                        <a href="#">Fashion</a></li>
                    <li id="menu-item-178"
                        class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-178"><a
                            href="#">Health</a></li>
                    <li id="menu-item-192"
                        class="menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-192">
                        <a href="#">Layout</a>
                        <ul class="sub-menu">
                            <li id="menu-item-196"
                                class="menu-item menu-item-type-post_type menu-item-object-page menu-item-196"><a
                                    href="http://demo.themegrill.com/colormag/left-sidebar/">Left Sidebar</a></li>
                            <li id="menu-item-195"
                                class="menu-item menu-item-type-post_type menu-item-object-page menu-item-195"><a
                                    href="http://demo.themegrill.com/colormag/right-sidebar/">Right Sidebar</a></li>
                            <li id="menu-item-194"
                                class="menu-item menu-item-type-post_type menu-item-object-page menu-item-194"><a
                                    href="http://demo.themegrill.com/colormag/no-sidebar-full-width/">No Sidebar Full
                                    Width</a></li>
                            <li id="menu-item-193"
                                class="menu-item menu-item-type-post_type menu-item-object-page menu-item-193"><a
                                    href="http://demo.themegrill.com/colormag/no-sidebar-content-centered/">No Sidebar
                                    Content Centered</a></li>
                        </ul>
                    </li>
                    <li id="menu-item-200" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-200">
                        <a href="#">View Pro</a>
                    </li>
                </ul>
            </div>
            <div class="random-post">
                <a href="#" title="View a random post"><i class="fa fa-random"></i></a>
            </div>
            <i class="fa fa-search search-top"></i>

            <div class="search-form-top">
                <form action="#" class="search-form searchform clearfix" method="get"
                      data-form-processed="true">
                    <div class="search-wrap">
                        <input type="text" placeholder="Search" class="s field" name="s">
                        <button class="search-icon" type="submit"></button>
                    </div>
                </form>
             </div>
        </div>
    </nav>
</div>